--- 
- name: Provisioning servers
  hosts: all
  become: yes
  vars:
    mydir: /opt/dir22
  tasks:
    - name: Install ntp agent on centos
      yum:
         name: "{{item}}"
         state: present
      when: ansible_distribution == "CentOS"
      loop:
        - chrony
        - wget
        - git
        - zip
        - unzip
    - name: Install ntp agent on ubuntu
      apt:
         name: "{{item}}"
         state: present
         update_cache: yes
      when: ansible_distribution == "Ubuntu"
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip
    - name: Start service on centos
      service:
         name: chronyd
         state: started
         enabled: yes
      when: ansible_distribution == "CentOS"
    - name: Start service on ubuntu
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"
    
    - name: Banner file
      copy:
        content: '#this server is managed by ansible. No manual changes please'
        dest: /etc/motd
    - name: Deploy ntp agent conf on centos
      template:
        src: templates/ntpconfs_centos
        dest: /etc/chrony.conf
        backup: yes
      when: ansible_distribution == "CentOS"
    - name: Deploy ntp agent conf on ubuntu
      template:
        src: templates/ntpconfs_ubuntu
        dest: /etc/ntp.conf
        backup: yes
      when: ansible_distribution == "CentOS"
    - name: reStart service on centos
      service:
        name: chronyd
        state: restarted
        enabled: yes
      when: ansible_distribution == "CentOS"
      notify: reStart service on centos
    - name: reStart service on ubuntu
      service:
        name: ntp
        state: restarted
        enabled: yes
      when: ansible_distribution == "Ubuntu"
    - name: Dump file
      copy: 
        src: files/myfile.txt
        dest: /tmp/myfile.txt
    - name: Create a folder
      file:
        path: "{{mydir}}"
        state: directory

  handlers: 
    - name: reStart service on centos
      service:
        name: chronyd
        state: restarted
        enabled: yes
      when: ansible_distribution == "CentOS"
    - name: reStart service on ubuntu
      service:
        name: ntp
        state: restarted
        enabled: yes
      when: ansible_distribution == "Ubuntu"



