---
- name: Understanding vars
  hosts: all
  become: yes
  vars:
    #USRNM: playuser
    #COMM: varibale from playbook
  tasks:
    - name: create user
      ansible.builtin.user:
        name: "{{USRNM}}"
        comment: "{{COMM}}"
      register: usrout
    - debug:
        var: usrout
    - debug: 
        msg: "{{USRNM}}"
    - debug:
        msg: "{{COMM}}"  
