---
- name: DBserver
  hosts: dataserver
  become: yes
  vars: 
    #dbname: accounts
    #dbuser: bob
    #dbpass: 12345
  tasks:
    - debug: 
        msg: "The dbname is-{{dbname}}"
    - debug:
        msg: "The dbname is-{{dbuser}}"
    - name: Install maria-server
      ansible.builtin.yum:
       name: mariadb-server
       state: present
    - name: Instal pymysql
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present
    - name: Start mariadb service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes
    - name: create a new database with name "accounts"
      mysql_db:
        name: "{{dbname}}"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
    - name: Create database user with name 'bob' and password '12345' with all database privileges
      community.mysql.mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock


